Map<String, String> countryCapitals = {
  'Andorra': 'Andorra la Vella',
  'Afghanistan': 'Kabul',
  'Albania': 'Tirana',
  'Algeria': 'Algiers',
  'American Samoa': 'Pago Pago',
  'Andorra': 'Andorra la Vella',
  'Angola': 'Luanda',
  'Anguilla': 'The Valley',
  'Antigua and Barbuda': 'St. John\'s',
  'Argentina': 'Buenos Aires',
  'Armenia': 'Yerevan',
  'Aruba': 'Oranjestad',
  'Australia': 'Canberra',
  'Austria': 'Vienna',
  'Azerbaijan': 'Baku',
  'Bahamas': 'Nassau',
  'Bahrain': 'Manama',
  'Bangladesh': 'Dhaka',
  'Barbados': 'Bridgetown',
  'Belarus': 'Minsk',
  'Belgium': 'Brussels',
  'Belize': 'Belmopan',
  'Benin': 'Porto-Novo',
  'Bermuda': 'Hamilton',
  'Bhutan': 'Thimphu',
  'Bolivia': 'La Paz',
  'Bonaire, Sint Eustatius and Saba': 'Kralendijk',
  'Bosnia and Herzegovina': 'Sarajevo',
  'Botswana': 'Gaborone',
  'Brazil': 'Brasília',
  'British Indian Ocean Territory': 'Diego Garcia',
  'Brunei Darussalam': 'Bandar Seri Begawan',
  'Bulgaria': 'Sofia',
  'Burkina Faso': 'Ouagadougou',
  'Burundi': 'Bujumbura',
  'Cambodia': 'Phnom Penh',
  'Cameroon': 'Yaoundé',
  'Canada': 'Ottawa',
  'Cape Verde': 'Praia',
  'Cayman Islands': 'George Town',
  'Central African Republic': 'Bangui',
  'Chad': 'N\'Djamena',
  'Chile': 'Santiago',
  'China': 'Beijing',
  'Christmas Island': 'Flying Fish Cove',
  'Cocos (Keeling) Islands': 'West Island',
  'Colombia': 'Bogotá',
  'Comoros': 'Moroni',
  'Congo': 'Brazzaville',
  'Cook Islands': 'Avarua',
  'Costa Rica': 'San José',
  'Croatia': 'Zagreb',
  'Cuba': 'Havana',
  'Curaçao': 'Willemstad',
  'Cyprus': 'Nicosia',
  'Czech Republic': 'Prague',
  'Côte d\'Ivoire': 'Yamoussoukro',
  'Denmark': 'Copenhagen',
  'Djibouti': 'Djibouti',
  'Dominica': 'Roseau',
  'Dominican Republic': 'Santo Domingo',
  'Ecuador': 'Quito',
  'Egypt': 'Cairo',
  'El Salvador': 'San Salvador',
  'Equatorial Guinea': 'Malabo',
  'Eritrea': 'Asmara',
  'Estonia': 'Tallinn',
  'Eswatini': 'Mbabane',
  'Ethiopia': 'Addis Ababa',
  'Falkland Islands (Malvinas)': 'Stanley',
  'Faroe Islands': 'Tórshavn',
  'Fiji': 'Suva',
  'Finland': 'Helsinki',
  'France': 'Paris',
  'French Guiana': 'Cayenne',
  'French Polynesia': 'Papeete',
  'Gabon': 'Libreville',
  'Gambia': 'Banjul',
  'Georgia': 'Tbilisi',
  'Germany': 'Berlin',
  'Ghana': 'Accra',
  'Gibraltar': 'Gibraltar',
  'Greece': 'Athens',
  'Greenland': 'Nuuk',
  'Grenada': 'St. George\'s',
  'Guadeloupe': 'Basse-Terre',
  'Guam': 'Hagåtña',
  'Guatemala': 'Guatemala City',
  'Guernsey': 'St. Peter Port',
  'Guinea': 'Conakry',
  'Guinea-Bissau': 'Bissau',
  'Guyana': 'Georgetown',
  'Haiti': 'Port-au-Prince',
  'Holy See': 'Vatican City',
  'Honduras': 'Tegucigalpa',
  'Hong Kong': 'Hong Kong',
  'Hungary': 'Budapest',
  'Iceland': 'Reykjavik',
  'India': 'New Delhi',
  'Indonesia': 'Jakarta',
  'Iran': 'Tehran',
  'Iraq': 'Baghdad',
  'Ireland': 'Dublin',
  'Isle of Man': 'Douglas',
  'Israel': 'Jerusalem',
  'Italy': 'Rome',
  'Jamaica': 'Kingston',
  'Japan': 'Tokyo',
  'Jersey': 'St. Helier',
  'Jordan': 'Amman',
  'Kazakhstan': 'Nur-Sultan',
  'Kenya': 'Nairobi',
  'Kiribati': 'Tarawa',
  'North Korea': 'Pyongyang',
  'South Korea': 'Seoul',
  'Kuwait': 'Kuwait City',
  'Kyrgyzstan': 'Bishkek',
  'Laos': 'Vientiane',
  'Latvia': 'Riga',
  'Lebanon': 'Beirut',
  'Lesotho': 'Maseru',
  'Liberia': 'Monrovia',
  'Libya': 'Tripoli',
  'Liechtenstein': 'Vaduz',
  'Lithuania': 'Vilnius',
  'Luxembourg': 'Luxembourg City',
  'Macao': 'Macao',
  'Madagascar': 'Antananarivo',
  'Malawi': 'Lilongwe',
  'Malaysia': 'Kuala Lumpur',
  'Maldives': 'Male',
  'Mali': 'Bamako',
  'Malta': 'Valletta',
  'Marshall Islands': 'Majuro',
  'Martinique': 'Fort-de-France',
  'Mauritania': 'Nouakchott',
  'Mauritius': 'Port Louis',
  'Mayotte': 'Mamoudzou',
  'Mexico': 'Mexico City',
  'Micronesia': 'Palikir',
  'Moldova': 'Chisinau',
  'Monaco': 'Monaco',
  'Mongolia': 'Ulaanbaatar',
  'Montenegro': 'Podgorica',
  'Montserrat': 'Plymouth',
  'Morocco': 'Rabat',
  'Mozambique': 'Maputo',
  'Myanmar': 'Naypyidaw',
  'Namibia': 'Windhoek',
  'Nauru': 'Yaren',
  'Nepal': 'Kathmandu',
  'Netherlands': 'Amsterdam',
  'New Caledonia': 'Nouméa',
  'New Zealand': 'Wellington',
  'Nicaragua': 'Managua',
  'Niger': 'Niamey',
  'Nigeria': 'Abuja',
  'Niue': 'Alofi',
  'Norfolk Island': 'Kingston',
  'North Macedonia': 'Skopje',
  'Northern Mariana Islands': 'Saipan',
  'Norway': 'Oslo',
  'Oman': 'Muscat',
  'Pakistan': 'Islamabad',
  'Palau': 'Ngerulmud',
  'Panama': 'Panama City',
  'Papua New Guinea': 'Port Moresby',
  'Paraguay': 'Asunción',
  'Peru': 'Lima',
  'Philippines': 'Manila',
  'Pitcairn': 'Adamstown',
  'Poland': 'Warsaw',
  'Portugal': 'Lisbon',
  'Puerto Rico': 'San Juan',
  'Qatar': 'Doha',
  'Romania': 'Bucharest',
  'Russia': 'Moscow',
  'Rwanda': 'Kigali',
  'Réunion': 'Saint-Denis',
  'Saint Barthélemy': 'Gustavia',
  'Saint Kitts and Nevis': 'Basseterre',
  'Saint Lucia': 'Castries',
  'Saint Martin (French part)': 'Marigot',
  'Saint Pierre and Miquelon': 'Saint-Pierre',
  'Saint Vincent and the Grenadines': 'Kingstown',
  'Samoa': 'Apia',
  'San Marino': 'San Marino',
  'Sao Tome and Principe': 'São Tomé',
  'Saudi Arabia': 'Riyadh',
  'Senegal': 'Dakar',
  'Serbia': 'Belgrade',
  'Seychelles': 'Victoria',
  'Sierra Leone': 'Freetown',
  'Singapore': 'Singapore',
  'Sint Maarten (Dutch part)': 'Philipsburg',
  'Slovakia': 'Bratislava',
  'Slovenia': 'Ljubljana',
  'Solomon Islands': 'Honiara',
  'Somalia': 'Mogadishu',
  'South Africa': 'Pretoria',
  'South Georgia and the South Sandwich Islands': 'King Edward Point',
  'South Sudan': 'Juba',
  'Spain': 'Madrid',
  'Sri Lanka': 'Colombo',
  'Sudan': 'Khartoum',
  'Suriname': 'Paramaribo',
  'Sweden': 'Stockholm',
  'Switzerland': 'Bern',
  'Syria': 'Damascus',
  'Taiwan': 'Taipei',
  'Tajikistan': 'Dushanbe',
  'Tanzania': 'Dodoma',
  'Thailand': 'Bangkok',
  'Timor-Leste': 'Dili',
  'Togo': 'Lomé',
  'Tokelau': 'Fakaofo',
  'Tonga': 'Nuku\'alofa',
  'Trinidad and Tobago': 'Port of Spain',
  'Tunisia': 'Tunis',
  'Turkey': 'Ankara',
  'Turkmenistan': 'Ashgabat',
  'Turks and Caicos Islands': 'Cockburn Town',
  'Tuvalu': 'Funafuti',
  'Uganda': 'Kampala',
  'Ukraine': 'Kyiv',
  'United Arab Emirates': 'Abu Dhabi',
  'United Kingdom': 'London',
  'United States': 'Washington, D.C.',
  'Uruguay': 'Montevideo',
  'Uzbekistan': 'Tashkent',
  'Vanuatu': 'Port Vila',
  'Venezuela': 'Caracas',
  'Vietnam': 'Hanoi',
  'Virgin Islands (British)': 'Road Town',
  'Virgin Islands (U.S.)': 'Charlotte Amalie',
  'Wallis and Futuna': 'Mata-Utu',
  'Western Sahara': 'El Aaiún',
  'Yemen': 'Sana\'a',
  'Zambia': 'Lusaka',
  'Zimbabwe': 'Harare',
};
